### ISSUE TITLE
No , Issue But question

### ISSUE THREAD

**Issue by jvboyle** [netmemo/nsxt-frac-tf-cm#1]
I'm trying to dynamically create a bunch of Service Groups and using your code ....Works great, but wonder if you have a way to loop threw and create 1 criteria with a conjunction in between ? 

Input file something like 
{
    "map_grp": {
        "joe-AP1-HOST-ap1d114lpnabwrk4": {
            "NAME": 
                [
                 "server1",
                 "server2"
                ],
            "IP": 
                [
                "192.168.1.100",
                "192.168.1.101"

                ]
        }
    }
 }

resource "nsxt_policy_group" "grp" {
   for_each = var.map_grp
   display_name = each.key
   nsx_id = each.key

  criteria {
    condition {
      key         = "Name"
      member_type = "VirtualMachine"
      operator    = "EQUALS"
      value       = "server1"
    }
  }

   conjunction {
      operator = "OR"
   }
   
   criteria {
    condition {
      key         = "Name"
      member_type = "VirtualMachine"
      operator    = "EQUALS"
      value       = "server2"
    }
  }

   dynamic "criteria" {
   for_each = { for key,val in each.value : key => val if key == "IP" }
      content {
         ipaddress_expression  {
            ip_addresses = criteria.value
         }
      }
   }
}

**Comment by netmemo** [comment]
Hello,

Yes, it can be done but in my opinion the data model is much more complex. In this example I've preferred to do something simple.
I can try to do a post on that more complex model if you want.

Regards,

Noël
